"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Clock, ControlSlider, Download, Filter, FrameAlt, OpenNewWindow, Search, Xmark } from "iconoir-react";

import { BeforeAfterSlider } from "@/components/generations/before-after-slider";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { ProductIcon } from "@/components/ui/product-icon";
import { GENERATION_STATUS_LABELS, ROOM_TYPE_LABELS, type GenerationStatus, type RoomType } from "@/lib/domain";
import type { AllGenerationsItem } from "@/services/generations";

// Images are private, short-lived signed URLs and cannot use a static next/image remote host.
/* eslint-disable @next/next/no-img-element */

function statusVariant(status: string) { if (status === "completed") return "default" as const; if (status === "failed") return "destructive" as const; if (status === "processing") return "outline" as const; return "secondary" as const; }
function formatDate(value: string) { return new Intl.DateTimeFormat("es-ES", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)); }

export function GenerationsHistoryView({ initialGenerations }: { initialGenerations: AllGenerationsItem[] }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [roomType, setRoomType] = useState("all"); const [comparison, setComparison] = useState<AllGenerationsItem | null>(null);
  const roomTypes = useMemo(() => Array.from(new Set(initialGenerations.map((item) => item.roomType).filter(Boolean))), [initialGenerations]);
  const filtered = useMemo(() => initialGenerations.filter((item) => { const haystack = `${item.propertyTitle} ${item.roomType} ${item.styleName}`.toLowerCase(); return (!query.trim() || haystack.includes(query.toLowerCase())) && (status === "all" || item.status === status) && (roomType === "all" || item.roomType === roomType); }), [initialGenerations, query, roomType, status]);
  const hasFilters = Boolean(query) || status !== "all" || roomType !== "all";
  const clear = () => { setQuery(""); setStatus("all"); setRoomType("all"); };
  return <div className="space-y-8">
    <section className="border-y border-border py-6"><div className="grid gap-3 lg:grid-cols-[minmax(16rem,1fr)_auto] lg:items-center"><div className="relative"><ProductIcon icon={Search} className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input aria-label="Buscar generaciones" placeholder="Buscar propiedad, estancia o estilo" value={query} onChange={(event) => setQuery(event.target.value)} className="h-11 pl-9" />{query && <button type="button" aria-label="Limpiar búsqueda" onClick={() => setQuery("")} className="absolute right-1 top-1/2 grid size-8 -translate-y-1/2 place-items-center text-muted-foreground transition-colors duration-[var(--motion-duration-control)] hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30"><ProductIcon icon={Xmark} className="size-4" /></button>}</div><div className="flex flex-wrap gap-2"><select aria-label="Filtrar por estado" value={status} onChange={(event) => setStatus(event.target.value)} className="h-11 rounded-md border border-input bg-background px-3 text-sm outline-none transition-[border-color,box-shadow] duration-[var(--motion-duration-control)] focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring/30"><option value="all">Todos los estados</option>{["completed","processing","pending","failed","cancelled"].map((value) => <option key={value} value={value}>{GENERATION_STATUS_LABELS[value as GenerationStatus]}</option>)}</select><select aria-label="Filtrar por estancia" value={roomType} onChange={(event) => setRoomType(event.target.value)} className="h-11 rounded-md border border-input bg-background px-3 text-sm outline-none transition-[border-color,box-shadow] duration-[var(--motion-duration-control)] focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring/30"><option value="all">Todas las estancias</option>{roomTypes.map((type) => <option key={type} value={type}>{ROOM_TYPE_LABELS[type as RoomType] ?? type}</option>)}</select>{hasFilters && <Button type="button" variant="ghost" size="sm" onClick={clear}><ProductIcon icon={Filter} className="size-3.5" />Limpiar</Button>}</div></div></section>
    <p aria-live="polite" className="text-xs text-muted-foreground">{filtered.length} de {initialGenerations.length} generaciones</p>
    {filtered.length === 0 ? <EmptyState icon={FrameAlt} title={hasFilters ? "No hay resultados para estos filtros" : "Aún no hay generaciones"} description={hasFilters ? "Prueba a cambiar los filtros para volver a ver el archivo de trabajo." : "Las propuestas visuales de tus habitaciones aparecerán aquí."} action={hasFilters ? <Button type="button" variant="outline" size="sm" onClick={clear}>Limpiar filtros</Button> : <Link href="/properties"><Button size="sm">Ir a propiedades</Button></Link>} /> : <div className="grid gap-x-8 divide-y divide-border border-y border-border md:grid-cols-2 md:divide-x md:divide-y-0 xl:grid-cols-3">{filtered.map((item) => <article key={item.id} className="group flex min-w-0 flex-col py-6 md:px-6 first:md:pl-0 last:xl:pr-0">
      <div className="relative aspect-[4/3] overflow-hidden bg-muted">{item.outputImageUrl && item.originalImageUrl ? <div className="grid size-full grid-cols-2"><img src={item.originalImageUrl} alt="Fotografía original" className="size-full object-cover" /><img src={item.outputImageUrl} alt={`Resultado ${item.styleName}`} className="size-full object-cover" /></div> : item.outputImageUrl ? <img src={item.outputImageUrl} alt={`Resultado ${item.styleName}`} className="size-full object-cover" /> : item.originalImageUrl ? <img src={item.originalImageUrl} alt="Fotografía original" className="size-full object-cover opacity-70" /> : <div className="grid size-full place-items-center text-xs text-muted-foreground">Sin vista previa</div>}<div className="absolute left-3 top-3"><Badge variant={statusVariant(item.status)}>{GENERATION_STATUS_LABELS[item.status as GenerationStatus] ?? item.status}</Badge></div>{item.outputImageUrl && item.originalImageUrl && <span className="absolute bottom-2 left-2 border border-white/40 bg-black/65 px-1.5 py-0.5 text-[0.625rem] font-medium uppercase tracking-[0.12em] text-white">Original · Resultado</span>}</div>
      <div className="flex flex-1 flex-col pt-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><Link href={`/properties/${item.propertyId}`} className="block truncate text-sm font-medium transition-colors hover:text-muted-foreground">{item.propertyTitle}</Link><Link href={`/properties/${item.propertyId}/rooms/${item.roomId}`} className="mt-1 block text-sm text-muted-foreground hover:text-foreground">{ROOM_TYPE_LABELS[item.roomType as RoomType] ?? item.roomType}</Link></div><Badge variant="secondary" className="shrink-0">{item.styleName}</Badge></div><p className="mt-4 flex items-center gap-1.5 text-xs text-muted-foreground"><ProductIcon icon={Clock} className="size-3.5" />{formatDate(item.createdAt)}</p>{item.status === "failed" && <p className="mt-3 text-sm text-muted-foreground">La generación no pudo completarse.</p>}<div className="mt-5 flex items-center justify-between border-t border-border pt-3">{item.status === "completed" && item.outputImageUrl && item.originalImageUrl ? <Button type="button" variant="ghost" size="sm" onClick={() => setComparison(item)}><ProductIcon icon={ControlSlider} className="size-3.5" />Comparar</Button> : <span />}{item.status === "completed" && item.outputImageUrl ? <a href={item.outputImageUrl} download={`generacion-${item.id}.png`} aria-label={`Descargar ${item.styleName}`}><Button variant="ghost" size="icon-xs"><ProductIcon icon={Download} className="size-3.5" /></Button></a> : <Link href={`/properties/${item.propertyId}/rooms/${item.roomId}`} aria-label="Abrir estancia"><ProductIcon icon={OpenNewWindow} className="size-4 text-muted-foreground" /></Link>}</div></div>
    </article>)}</div>}
    {comparison?.outputImageUrl && comparison.originalImageUrl && <div className="fixed inset-0 z-50 flex flex-col bg-background/95 p-4 backdrop-blur-md sm:p-6"><div className="flex items-start justify-between gap-4 border-b border-border pb-4"><div><p className="text-label">Comparación</p><h2 className="mt-2 text-heading font-medium">{comparison.propertyTitle} · {comparison.styleName}</h2></div><Button type="button" variant="outline" size="sm" onClick={() => setComparison(null)}><ProductIcon icon={Xmark} className="size-4" />Cerrar</Button></div><div className="min-h-0 flex-1 py-5"><BeforeAfterSlider originalUrl={comparison.originalImageUrl} stagedUrl={comparison.outputImageUrl} title={`${comparison.propertyTitle} · ${comparison.styleName}`} /></div></div>}
  </div>;
}
